language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2

bundler_args: --without integration development

before_script:
  - bundle exec berks

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
